# -*- coding: utf-8 -*-
"""NewIdea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15i5NRAc4ClaYo4mrO7B4BmorkBjUk5AD
"""

import numpy as np
import matplotlib.pyplot as plt
from typing import Callable, List, Tuple

sixtyfour_bit_minimum = -9223372036854775808
sixtyfour_bit_maximum = 9223372036854775807

"""
this program models natural selection on the level of individuals taking into
account biological noise.

individuals are all haploid and each parent makes children alone through cloning
(involving mutation)

population size can vary

the generations are cyclical, so everyone reproduces (or not) then dies before
the new generation is born

it takes as input (1) the population and (2) a lambda equation that dictates the
fitness of each phenotype at each generation, the form of the equation is
fitness = function of phenotype and time

the fitness number computed by these lamda equations tells you the average expected number of
offspring that an individual with that phenotype is expected to produce at that generation in time

time, t, is measured in generations

all of the population is stored in a matrix:

rows: info about each individual
                                  -amount of noise (float 0 to 1)
                                  -phenotype (represented by int)
                                  -genotype (represented by int)
collumns: each individual (unlabelled)

phenotypes are on the line of integers. they represent a physical quality that
can be shown on a scale. for example beak size or amount of pigmentation

how many offspring a parent has is determined based on the fitness of its
phenotype (and also randomness)

phenotypes are determined by genotypes. in this model, genotype 7 is most likely
to result in phenotype 7 but could also likely result in phenotype 6 or 8,
for example. the probabilities at which this occurs can be tuned in the model.
the amount of noise affects how likely the phenotype is to match the genotype.

both genotypes and amount of noise are passed down directly from parent to child
unless there is a mutation. the more noise, the more likely a mutation.

noise of 0 means that offspring are always identical to parent

noise of 1 (realistically impossible but possible in the simulation) means that
offspring inherit completely random genotypes, independent of their parents.
in this simulation, i put the
limit that no matter how high the noise, the genotype of a new individual cannot
be more than 5 ints away from the highest or lowest individual in the population
otherwise, a population with noise of 0.99999 could theoretically go from having
all genotypes in the -7 to 13 range in one generation then end up with an
organism with a genotype labelled 3553 the very next generation. the "5" is
a random placeholder, and next steps include figuring out what this value
should actually represent

"""


class Population:
    def __init__(self, initial_genotypes: np.ndarray, initial_noise_levels: np.ndarray):
        # initialize population matrix:
        # row 0: amount of noise (float 0 to 1)
        # row 1: phenotype (represented by int)
        # row 2: genotype (represented by int)

        size = initial_genotypes.shape[0]

        if initial_genotypes.shape[0] != initial_noise_levels.shape[0]:
            raise ValueError("initial genotypes and noise levels must be same length")

        self.population = np.zeros((3, size), dtype=object) # dtype allows mixed types
        self.population[0, :] = initial_noise_levels.astype(float) # noise
        self.population[2, :] = initial_genotypes.astype(int)   # genotypes
        self.calculate_phenotypes() # calculate initial phenotypes

    def calculate_phenotypes(self):
        #this function calculates the phenotypes based on noise and genotypes
        # direct mapping
        # uses a normal distribution for now (can later be changed)
        genotypes = self.population[2, :].astype(int)
        noise_levels = self.population[0, :].astype(float)

        std_dev = noise_levels * 2
        phenotype_deviation = np.random.normal(loc=0, scale=std_dev, size=genotypes.shape)
        self.population[1, :] = (genotypes + phenotype_deviation).round().astype(int)

    def get_fitness(self, fitness_function: Callable[[int, int], float], current_time: int, max_population_size: int) -> np.ndarray:
        #this function calculates the fitness of each individual

        phenotypes = self.population[1, :].astype(int) # Ensure phenotypes are int for fitness function
        fitness_scores = np.array([fitness_function(p, current_time) for p in phenotypes])
        # Replace any NaN, positive infinity, or negative infinity values
        # Positive infinity is capped at max_population_size * 2 to prevent OverflowError during int conversion
        # Negative infinity is replaced by 0.0
        fitness_scores = np.nan_to_num(fitness_scores, nan=0.0, posinf=float(max_population_size * 2), neginf=0.0)
        # Ensure fitness scores are never below a minimum value (0.0) and are also capped at a maximum
        return np.clip(fitness_scores, 0.0, float(max_population_size * 2))

    def reproduce(self, fitness_scores: np.ndarray, max_population_size: int) -> np.ndarray:
        # this function selects parents based on fitness then generates
        # offspring to return a new population matrix. the population size varies.

        current_pop_size = self.population.shape[1]

        # if current pop is empty, it cannot reproduce
        if current_pop_size == 0:
            return np.zeros((3, 0), dtype=object)

        # determine new pop size based on overall reproductive potential
        total_reproductive_potential = np.sum(fitness_scores)
        desired_new_pop_size = int(round(total_reproductive_potential))

        # Cap the new population size
        new_pop_size = min(desired_new_pop_size, max_population_size)

        if new_pop_size <= 0:
            return np.zeros((3, 0), dtype=object) # population goes extinct

        # probabilities for parent selection
        probabilities = fitness_scores / total_reproductive_potential

        # parents chosen based on fitness-proportional selection
        parent_indices = np.random.choice(current_pop_size, size=new_pop_size, p=probabilities)

        new_population_data = np.zeros((3, new_pop_size), dtype=object)

        min_genotype = np.min(self.population[2, :])
        max_genotype = np.max(self.population[2, :])

        for index, parent_index in enumerate(parent_indices):
            parent_noise = self.population[0, parent_index]
            parent_genotype = self.population[2, parent_index]

            # mutation step
            mutation_chance = parent_noise # noise as mutation chance

            if np.random.rand() < mutation_chance:
                # mutation occurs

                # Calculate bounds for new genotype based on population's current genotype range
                # and the '5 ints away' limit
                lower_bound = max(min_genotype - 5, sixtyfour_bit_minimum)
                upper_bound = min(max_genotype + 5, sixtyfour_bit_maximum)

                # if noise=1, totally random within bounds
                if parent_noise >= 1.0:
                    new_genotype = np.random.randint(lower_bound, upper_bound + 1)
                    new_noise = np.random.rand()
                    # technically new_noise should be able to hpothetically be 1.0
                    # in this case but the chance of that happening is so incredibly small
                    # that we can use np.random.rand() (which prevents this from ever happening)
                    # because np.random.rand() is more efficient than np.random.uniform(0.0,1.0)

                else:
                    # 0 < noise < 1 : mutation is a deviation from parent genotype
                    # deviation magnitude scaled by noise

                    deviation_range = int(round(parent_noise * 5)) + 1
                    # max deviation increases with noise
                    # that 5 is  arbitrary, next steps include figuring out what it should actually be

                    deviation = np.random.randint(-deviation_range, deviation_range + 1)
                    new_genotype = int(parent_genotype + deviation)
                    # ensure new genotype stays within the bounds
                    new_genotype = max(lower_bound, min(new_genotype, upper_bound))

                    new_noise = deviation / 6 + parent_noise
                    # The noise level must be between 0 and 1.
                    # Clamp the calculated new_noise to be within [0, 1].
                    new_noise = np.clip(new_noise, 0.0, 1.0)
                    # the 6 must be changed if the 5 above is changed,
                    # here's the reason why it was chosen:
                    # if the parent_noise is 1, then the deviation range is 5+1 = 6,
                    # then the deviation variable can be up to 6, but we want in
                    # that case for the deviation variable to be up to 1, so we
                    # divide by 6

            else:
                # offspring is clone of parent
                new_genotype = parent_genotype
                new_noise = parent_noise

            new_population_data[0, index] = new_noise
            new_population_data[2, index] = new_genotype

        # a new Population object is created directly with new gen's data
        # pass numpy arrays directly
        new_generation_pop = Population(new_population_data[2, :].astype(int), new_population_data[0, :].astype(float))

        return new_generation_pop.population

    def evolve(self, generations: int, fitness_function: Callable[[int, int], float], max_population_size: int):
        # simulates evolution over lots of generations.
        history = [] # store population states over time

        for t in range(generations):
            history.append({
                'generation': t,
                'genotypes': self.population[2, :].copy(),
                'phenotypes': self.population[1, :].copy(),
                'noise_levels': self.population[0, :].copy()
            })

            fitness_scores = self.get_fitness(fitness_function, t, max_population_size)
            self.population = self.reproduce(fitness_scores, max_population_size)
            self.calculate_phenotypes() # re-calculate phenotypes for new gen

        history.append({
            'generation': generations,
            'genotypes': self.population[2, :].copy(),
            'phenotypes': self.population[1, :].copy(),
            'noise_levels': self.population[0, :].copy()
        })

        return history


def run_single_simulation(
    pop_size: int,
    initial_genotypes_generator: Callable[[int], np.ndarray],
    initial_noise_levels_generator: Callable[[int], np.ndarray],
    generations_to_simulate: int,
    fitness_function: Callable[[int, int], float],
    plot: bool = True,
    plot_title_suffix: str = "",
    max_population_size: int = 1000 # New parameter with default
) -> Tuple[List[dict], bool, int]:
    """runs one evolutionary simulation, plots avg genotype and noise, and checks fixation.

    Args:
        pop_size: size of the population.
        initial_genotypes_generator: function that takes pop_size and returns an np.ndarray of initial genotypes.
        initial_noise_levels_generator: function that takes pop_size and returns an np.ndarray of initial noise levels.
        generations_to_simulate: The number of generations to simulate.
        fitness_function: The fitness function to use for the simulation.
        plot: Whether to display plots for this single simulation.
        plot_title_suffix: An optional suffix to add to the plot titles.
        max_population_size: The maximum population size allowed in the simulation.

    Returns:
        A tuple containing:
            - evolution_history: A list of dictionaries, each describing a generation.
            - fixed: A boolean indicating if fixation occurred.
            - fixation_gen: The generation at which fixation occurred, or -1 if no fixation.
    """

    initial_genotypes = initial_genotypes_generator(pop_size)
    initial_noise_levels = initial_noise_levels_generator(pop_size)

    my_population = Population(initial_genotypes, initial_noise_levels)

    if plot:
        print(f"Simulation Start (Initial Pop Size: {pop_size}, Gen: {generations_to_simulate})")
        print("Initial pop (genotypes):", my_population.population[2, :])
        print("Initial pop (phenotypes):", my_population.population[1, :])
        print("Initial pop (noise levels):", my_population.population[0, :])

    evolution_history = my_population.evolve(generations_to_simulate, fitness_function, max_population_size)

    fixed = False
    fixation_gen = -1
    for gen_data in evolution_history:
        genotypes_at_gen = gen_data['genotypes']
        # check if pop is not empty before checking fixation
        if len(genotypes_at_gen) > 0 and len(np.unique(genotypes_at_gen)) == 1:
            fixed = True
            fixation_gen = gen_data['generation']
            break # found fixation

    if plot:
        final_genotypes = evolution_history[-1]['genotypes']
        final_phenotypes = evolution_history[-1]['phenotypes']
        final_noise_levels = evolution_history[-1]['noise_levels']

        print("\nFinal pop (genotypes):", final_genotypes)
        print("Final pop (phenotypes):", final_phenotypes)
        print("Final pop (noise levels):", final_noise_levels)
        print(f"Simulation End (Final Pop Size: {len(final_genotypes)}, Gen: {generations_to_simulate})\n")

        # plotting avg genotype over generations
        avg_genotypes = [np.mean(gen_data['genotypes']) if len(gen_data['genotypes']) > 0 else np.nan for gen_data in evolution_history]
        plt.figure(figsize=(12, 5))
        plt.subplot(1, 2, 1) # Create a subplot for genotype
        plt.plot([h['generation'] for h in evolution_history], avg_genotypes)
        plt.xlabel("Generation")
        plt.ylabel("Average Genotype")
        plt.title(f"Evolution of Average Genotype{plot_title_suffix}")
        plt.grid(True)

        # plotting average noise levels over generations
        avg_noise_levels = [np.mean(gen_data['noise_levels']) if len(gen_data['noise_levels']) > 0 else np.nan for gen_data in evolution_history]
        plt.subplot(1, 2, 2) # create a subplot for noise levels
        plt.plot([h['generation'] for h in evolution_history], avg_noise_levels, color='orange')
        plt.xlabel("Generation")
        plt.ylabel("Average Noise Level")
        plt.title(f"Evolution of Average Noise Level{plot_title_suffix}")
        plt.grid(True)

        plt.tight_layout() # adjust layout to prevent overlapping titles/labels
        plt.show()

    return evolution_history, fixed, fixation_gen

def run_multiple_simulations(
    pop_size: int,
    initial_genotypes_generator: Callable[[int], np.ndarray],
    initial_noise_levels_generator: Callable[[int], np.ndarray],
    generations_to_simulate: int,
    fitness_function: Callable[[int, int], float],
    num_simulations: int,
    max_population_size: int = 1000 # New parameter with default
):
    """Runs multiple evolutionary simulations, reports fixation statistics, and plots overall trends.

    Args:
        pop_size: size of the initial population
        initial_genotypes_generator: function that takes pop_size and returns an np.ndarray of initial genotypes
        initial_noise_levels_generator: function that takes pop_size and returns an np.ndarray of initial noise levels
        generations_to_simulate: number of generations to simulate
        fitness_function: gives the fitness of each phenotype at each generation
        num_simulations: number of independent simulations to run
        max_population_size: The maximum population size allowed in the simulation.
    """

    all_avg_genotypes_runs = []
    all_avg_noise_levels_runs = []
    fixation_generations = []
    fixed_count = 0

    print(f"running {num_simulations} simulations...")

    for i in range(num_simulations):
        # run each simulation without plotting individually
        evolution_history, fixed, fixation_gen = run_single_simulation(
            pop_size, initial_genotypes_generator, initial_noise_levels_generator,
            generations_to_simulate, fitness_function, plot=False, max_population_size=max_population_size
        )

        # calculate avg genotypes and noise for the current run
        avg_genotypes_current_run = [np.mean(gen_data['genotypes']) if len(gen_data['genotypes']) > 0 else np.nan for gen_data in evolution_history]
        avg_noise_levels_current_run = [np.mean(gen_data['noise_levels']) if len(gen_data['noise_levels']) > 0 else np.nan for gen_data in evolution_history]

        all_avg_genotypes_runs.append(avg_genotypes_current_run)
        all_avg_noise_levels_runs.append(avg_noise_levels_current_run)

        if fixed:
            fixed_count += 1
            fixation_generations.append(fixation_gen)

        if (i+1) % 100 == 0:
            print(f"Simulation {i+1}/{num_simulations} completed. Fixation: {fixed}, Gen: {fixation_gen}")

    percentage_fixed = (fixed_count / num_simulations) * 100
    avg_fixation_gen = np.mean(fixation_generations) if fixation_generations else 0

    print(f"\nMultiple Simulations Summary ({num_simulations} runs)")
    print(f"Percentage of scenarios with fixation: {percentage_fixed:.2f}%")
    print(f"Average generation of fixation (for fixed scenarios): {avg_fixation_gen:.2f}")

    # plotting overall averages
    plt.figure(figsize=(12, 5))
    generations_axis = list(range(generations_to_simulate + 1))

    # average genotype plot
    plt.subplot(1, 2, 1)
    for run_data in all_avg_genotypes_runs:
        plt.plot(generations_axis, run_data, color='blue', linewidth=0.1)
    overall_avg_genotypes = np.nanmean(all_avg_genotypes_runs, axis=0)
    plt.plot(generations_axis, overall_avg_genotypes, color='green', linewidth=1, label='Mean Genotype')
    plt.xlabel("Generation")
    plt.ylabel("Average Genotype")
    plt.title("Overall Evolution of Average Genotype (Multiple Runs)")
    plt.grid(True)
    plt.legend()

    # avg noise amount plot
    plt.subplot(1, 2, 2)
    for run_data in all_avg_noise_levels_runs:
        plt.plot(generations_axis, run_data, color='orange', linewidth=0.1)
    overall_avg_noise_levels = np.nanmean(all_avg_noise_levels_runs, axis=0)
    plt.plot(generations_axis, overall_avg_noise_levels, color='red', linewidth=1, label='Mean Noise Level')
    plt.xlabel("Generation")
    plt.ylabel("Average Noise Level")
    plt.title("Overall Evolution of Average Noise Level (Multiple Runs)")
    plt.grid(True)
    plt.legend()

    plt.tight_layout()
    plt.show()


# EXAMPLES

# phenotypes first, time second in the lamda fitness functions

# define how to generate initial genotypes and noise levels for default simulation
def default_initial_genotypes(size):
    return np.random.randint(5, 15, size=size)

def default_initial_noise_levels(size):
    return np.random.uniform(0.1, 0.5, size=size)

print("\nExample 1: Running a single simulation with time independent fitness, increasing population")
run_single_simulation(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: 2 * (1 - ((a - 10) / 5))**2,
    plot=True,
    max_population_size=1000 # Added max population size
)

print("\nExample 2: Running a single simulation with time independent fitness, somewhat stable population size")
run_single_simulation(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: (1 - ((a - 10) / 5))**2,
    plot=True,
    max_population_size=1000 # Added max population size
)

print("\nExample 3: Running a single simulation with time independent fitness, decreasing population")
run_single_simulation(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: (1 - ((a - 10) / 5)**2) / 2,
    plot=True,
    max_population_size=1000 # Added max population size
)

print("\nExample 4: Running multiple simulations with time independent fitness, increasing population")
run_multiple_simulations(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: 2 * (1 - ((a - 10) / 5))**2,
    num_simulations=5,
    max_population_size=1000 # Added max population size
)

print("\nExample 5: Running multiple simulations with time independent fitness, somewhat stable population size")
run_multiple_simulations(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: (1 - ((a - 10) / 5))**2,
    num_simulations=5,
    max_population_size=1000 # Added max population size
)


print("\nExample 6: Running multiple simulations with time independent fitness, decreasing population")
run_multiple_simulations(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=500,
    fitness_function=lambda a, b: (1 - ((a - 10) / 5)**2) / 2,
    num_simulations=5,
    max_population_size=1000 # Added max population size
)

print("\nExample 7: Running multiple simulations with time dependent fitness, quadratic based")
run_multiple_simulations(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=5000,
    fitness_function=lambda a, b: (1 - ((a - 10) / 10 / b))**2,
    num_simulations=50,
    max_population_size=1000 # Added max population size
)

print("\nExample 8: Running multiple simulations with time dependent fitness, trig based")
run_multiple_simulations(
    pop_size=100,
    initial_genotypes_generator=default_initial_genotypes,
    initial_noise_levels_generator=default_initial_noise_levels,
    generations_to_simulate=1000,
    fitness_function=lambda a, b: 1 + np.sin(2 * np.pi * a * b),
    num_simulations=50,
    max_population_size=1000 # Added max population size
)